- name: vars in inventory
  hosts: local
  connection: local
  tasks:
  - name: print variables from inventory
    ansible.builtin.debug:
      msg: "course is {{course}}, duration is {{duration}}, trainer is {{trainer}}"