- name: default Variables
  hosts: web
  connection: local
  tasks:
  - name: print default variables
    ansible.builtin.debug:
      msg: "{{person | default('Kiran')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, guva"
    ansible.builtin.debug:
      msg: "fruit list : {{fruits | split(',')}}"