- name: default Variables
  hosts: web
  connection: local
  tasks:
  - name: print default variables
    ansible.builtin.debug:
      msg: "{{person | default('Kiran')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, guva"
    ansible.builtin.debug:
      msg: "fruit list : {{fruits | split(',')}}"

  - name: convert map to list
    vars:
      course:
        name: devops
        duration: 120
        trainer: kiran
    ansible.builtin.debug:
      msg: "course is : {{course | dict2items}}"