- name: default Variables
  hosts: web
  connection: local
  tasks:
  - name: print default variables
    ansible.builtin.debug:
      msg: "{{person | default('Kiran')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, guva"
    ansible.builtin.debug:
      msg: "fruit list : {{fruits | split(',')}}"

  - name: convert map to list
    vars:
      course:
        name: devops
        duration: 120
        trainer: kiran
    ansible.builtin.debug:
      msg: "course is : {{course | dict2items}}"

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'ravi'}
    ansible.builtin.debug:
      msg: "colurse map is {{course | items2dict}}"
    
  - name: convert lower to upper
    vars:
      name: "ravi prakash reddy"
    ansible.builtin.debug:
      msg: "upper case name : {{name | upper}}"

  - name: min and max
    vars:
      num: [1,3,43,567,98554]
    ansible.builtin.debug:
      msg: "min is : {{num | min}},   max is : {{num | max}}"

  -name: valid IP or not
   vars:
    ip: "2.45.234.32"
   ansible.builtin.debug:
    msg: "{{ip | ansible.util.ipaddr}}"
  